import java.util.Arrays;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {

        System.out.println("-".repeat(18) + "\nArrays Challenge 1\n" + "-".repeat(18));
        System.out.println("\nSorting an array of integers in descending order\n" + "-".repeat(48));
        //Initializing a new array with the array generated by the user through the method.
        int[] array1 = populatedArray();
        System.out.println(Arrays.toString(array1));

        sortedArray(array1);
    }

    private static int[] populatedArray() {
        //Creating a scanner object.
        Scanner scanner = new Scanner(System.in);
        System.out.println("Please enter the size of the array");
        //Reading the user's chosen size of array.
        int userChosenSizeOfArray = scanner.nextInt();
        //Creating an array that will store the user's integer values.
        int[] populatedUserArray = new int[userChosenSizeOfArray];
        //Populating the user's array based on user's chosen size of array.
        for (int i = 0; i < userChosenSizeOfArray; i++) {
            System.out.println("Please enter the integer values to be stored in your array");
            //Storing the entered integer value inside the element[i] of populatedUserArray's array.
            populatedUserArray[i] = scanner.nextInt();
            populatedUserArray[i] *= -1;
        }
        //Returning the populated array for further usage.
        return populatedUserArray;
    }

    private static void sortedArray(int[] array) {

        int[] arrayForStoringSortedArray = Arrays.copyOf(array, array.length);
        //Sorting the array in ascending order.
        Arrays.sort(arrayForStoringSortedArray);

        for (int i = 0; i < array.length; i++) {
            arrayForStoringSortedArray[i] *= -1;
        }

        System.out.println("Printing the sorted array in DESCENDING ORDER: \n" +
                Arrays.toString(arrayForStoringSortedArray));;
    }

}